import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  // variable: "latun",
  subsets: ["latin"],
  weight: ['400', '700']
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/logo.png"
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={` ${roboto.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
